pipeline:
  test:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ln -s /var/cache/drone/scala-scala scala-scala
      - ./scripts/update-scala-library
      - sbt -J-Xmx4096m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m -Ddotty.drone.mem=4096m -ivy /var/cache/drone/ivy2 "${TEST}"
    when:
      branch:
        exclude: gh-pages

  documentation:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ./project/scripts/genDocs "${TEST}" $BOT_PASS
    when:
      branch: master

  slack:
    image: plugins/slack
    channel: dotty
    webhook: $SLACK_WEBHOOK
    when:
      branch: master

matrix:
  TEST:
    - test
    - ;publishLocal;dotty-bootstrapped/test
    - partest-only-no-bootstrap --show-diff --verbose
    - partest-only --show-diff --verbose
