# After updating this file, you need to re-sign it:
#
# - Install [drone-cli](http://readme.drone.io/usage/getting-started-cli/)
# - Copy your token from  http://dotty-ci.epfl.ch/account (Click SHOW TOKEN)
# - (export DRONE_TOKEN=your-token; export DRONE_SERVER=http://dotty-ci.epfl.ch; drone sign lampepfl/dotty)

pipeline:
  test:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ln -s /var/cache/drone/scala-scala scala-scala
      - ln -s /var/cache/drone/ivy2 "$HOME/.ivy2"
      - ./scripts/update-scala-library
      - sbt -J-Xmx4096m -J-XX:ReservedCodeCacheSize=512m -J-XX:MaxMetaspaceSize=1024m -Ddotty.drone.mem=4096m "${TEST}"
    when:
      branch:
        exclude: gh-pages

  documentation:
    image: lampepfl/dotty:latest
    pull: true
    commands:
      - ./project/scripts/genDocs "${TEST}" $BOT_PASS
    when:
      branch: master

  gitter:
    image: plugins/gitter
    when:
      branch: master
      status: changed

  slack:
    image: plugins/slack
    channel: dotty
    when:
      branch: master
      status: changed

matrix:
  TEST:
    - dotty-bin-tests/test
    - legacyTests
    - test
    - ;publishLocal ;dotty-bootstrapped/test
