###################################################################################################
###                                  OFFICIAL RELEASE WORKFLOW                                  ###
### HOW TO USE:                                                                                 ###
###   - THIS WORKFLOW WILL NEED TO BE TRIGGERED MANUALLY                                        ###
###                                                                                             ###
### NOTE:                                                                                       ###
###   - THIS WORKFLOW SHOULD ONLY BE RUN ON STABLE RELEASES                                     ###
###   - IT ASSUMES THAT THE PRE-RELEASE WORKFLOW WAS PREVIOUSLY EXECUTED                        ###
###                                                                                             ###
###################################################################################################

name: Official release of Scala
run-name: Official release of Scala ${{ inputs.version }}

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version to officially release'
        required: true
        type: string

jobs:
  # TODO: ADD JOB TO SWITCH THE GITHUB RELEASE FROM DRAFT TO LATEST
  publish-sdkman:
    uses:  ./.github/workflows/publish-sdkman.yml
    with:
      version: ${{ inputs.version }}
    secrets:
      CONSUMER-KEY: ${{ secrets.SDKMAN_KEY }}
      CONSUMER-TOKEN: ${{ secrets.SDKMAN_TOKEN }}

  publish-winget:
    uses: ./.github/workflows/publish-winget.yml
    with:
      version: ${{ inputs.version }}
    secrets:
      DOTTYBOT-TOKEN: ${{ secrets.DOTTYBOT_WINGET_TOKEN }}

  build-chocolatey:
    uses: ./.github/workflows/build-chocolatey.yml
    with:
      version: ${{ inputs.version }}
      url    : 'https://github.com/scala/scala3/releases/download/${{ inputs.version }}/scala3-${{ inputs.version }}-x86_64-pc-win32.zip'
  test-chocolatey:
    uses: ./.github/workflows/test-chocolatey.yml
    needs: build-chocolatey
    with:
      version     : ${{ inputs.version }}
      java-version: 8
  publish-chocolatey:
    uses: ./.github/workflows/publish-chocolatey.yml
    needs: [ build-chocolatey, test-chocolatey ]
    with:
      version: ${{ inputs.version }}
    secrets:
      API-KEY: ${{ secrets.CHOCOLATEY_KEY }}

  # TODO: ADD RELEASE WORKFLOW TO CHOCOLATEY AND OTHER PACKAGE MANAGERS HERE