name: CI for scala3doc

on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow --tags

      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Compile and test
        run: ./project/scripts/sbt scala3doc-test/test

      - name: Locally publish self
        run: ./project/scripts/sbt scala3doc/publishLocal

      - name: Generate test documentation
        run: ./project/scripts/sbt scala3doc/generateSelfDocumentation

      - name: Generate Scala 3 documentation
        run: ./project/scripts/sbt scala3doc/generateScala3Documentation

      - name: Generate documentation for example project using dotty-sbt
        run: |
          ./project/scripts/sbt ";sbt-dotty/publishLocal;scala3/publishLocal;publishLocal"
          VERSION=$(./project/scripts/sbt "show sbt-dotty/version" | tail -1 | sed 's/\[info\] //')
          echo Using sbt-dotty version: $VERSION
          echo 'addSbtPlugin("ch.epfl.lamp" % "sbt-dotty" % "'$VERSION'")' > scala3doc/example-project/project/dotty.sbt

          SCALA_VERSION=$(./project/scripts/sbt "show scala3-compiler-bootstrapped/version" | tail -1 | sed 's/\[info\] //')
          echo Using scala version: $SCALA_VERSION
          echo 'scalaVersion := "'$SCALA_VERSION'"' > scala3doc/example-project/dotty.sbt

          cd scala3doc/example-project
          sbt doc
