name: Specification

on:
  push:
    tags:
      - '*'
    branches-ignore:
      - 'gh-readonly-queue/**'
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  DOTTY_CI_RUN: true

jobs:
  specification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs/_spec

    steps:
      - uses: actions/checkout@v3

      # Keep in sync with ./docs/_spec/Dockerfile
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - name: Install required gems
        run: |
          gem update --system
          gem install sass-embedded -v 1.58.0
          gem install bundler:1.17.2 jekyll
          bundle install
          npm install bower

      - name: Build the specification
        run: |
          bundle exec jekyll build
